version: '3.8'
services:
  wsusoffline:
    image: r0gger/docker-wsusoffline:latest
    #image: r0gger/docker-wsusoffline:ce
    container_name: wsusoffline
    volumes:
      - wsusoffline_updates:/client
    environment:
      - SYSTEMS=w100-x64
      - LANGUAGE=enu
      - PARAMS=-includesp -includecpp -includedotnet -includewddefs8
      - ISO=no
      - SLEEP=48h
      - DOWNLOADERS=ariaia2c wget
    restart: unless-stopped

volumes:
  wsusoffline_updates:
    driver: local
