supported_downloaders="aria2c wget"
proxy_server=""
secure_proxy_server=""
no_proxy_server=""
prefer_seconly="disabled"
check_for_self_updates="enabled"
unattended_updates="enabled"
include_win_glb="enabled"
use_file_signature_verification="disabled"
use_integrity_database="enabled"
use_cleanup_function="enabled"
debug="disabled"
exit_on_configuration_problems="enabled"
return 0
